/* TODOS CONSTS */

const ADD_TODO = 'ADD_TODO';
const DELETE_TODO = 'DELETE_TODO';
const DONE_TODO = 'DONE_TODO';
const SWITCH_TODO_HOUR = 'SWITCH_TODO_HOUR';


/* TODOS CONSTS */

const OPEN_HOUR_MODAL = 'OPEN_HOUR_MODAL';


export {
  ADD_TODO,
  DELETE_TODO,
  DONE_TODO,
  SWITCH_TODO_HOUR,
  OPEN_HOUR_MODAL
};
