/* TODOS CONSTS */

const ADD_TODO = 'ADD_TODO';
const DELETE_TODO = 'DELETE_TODO';
const DONE_TODO = 'DONE_TODO';
const SWITCH_TODO_HOUR = 'SWITCH_TODO_HOUR';


const CUSTOM_ADD_TODO = 'CUSTOM_ADD_TODO';
const CUSTOM_DELETE_TODO = 'CUSTOM_DELETE_TODO';
const CUSTOM_DONE_TODO = 'CUSTOM_DONE_TODO';


/* TODOS CONSTS */

const OPEN_HOUR_MODAL = 'OPEN_HOUR_MODAL';


export {
  ADD_TODO,
  DELETE_TODO,
  DONE_TODO,
  SWITCH_TODO_HOUR,
  OPEN_HOUR_MODAL,
  CUSTOM_ADD_TODO,
  CUSTOM_DELETE_TODO,
  CUSTOM_DONE_TODO
};
